server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080  #sentinel dashboard
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，甚至找到未被占用的端口
        port: 8719
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            rule-type: flow

# nacos 地址
#spring.cloud.sentinel.datasource.ds.nacos.server-addr=localhost:8848
#spring.cloud.sentinel.datasource.ds.nacos.dataId=${spring.application.name}-sentinel
#spring.cloud.sentinel.datasource.ds.nacos.groupId=DEFAULT_GROUP
# 规则类型
#spring.cloud.sentinel.datasource.ds.nacos.rule-type=flow


management:
  endpoints:
    web:
      exposure:
        include: '*'

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true



