server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.201:1111
        #配置nacos地址
        #server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

