###consul服务
server:
  port: 8006

spring:
  application:
    name: consul-payment-provider
  #consul 注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
